pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
    path('<int:_id>/', views.detail, name='detail'),
    path('<int:_id>/update/', views.update, name='update'),
    path('<int:_id>/delete/', views.delete, name='delete'),
]

reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    movie_name = models.CharField(max_length=30)
    grade = models.FloatField(validators=[MinValueValidator(0.0),MaxValueValidator(5.0)])
    star = models.CharField(max_length=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    

reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):

    class Meta():
        model = Review
        fields = ['title', 'content', 'movie_name', 'grade']

reviews/views.py
from django.shortcuts import redirect, render
from .models import Review
from .forms import ReviewForm
from django.core.paginator import Paginator


def create(req):
    if req.method == 'POST':
        data = ReviewForm(req.POST)

        if data.is_valid():
            # form 으로 부터 받은 데이터를 가져오기
            db_data = data.save(commit=False)

            # 0 ~ 5 까지의 별점
            for i in range(6):
                if db_data.grade == 0:
                    db_data.star = '☆' * 5
                    break
                # 정수일 때 i 만큼 ★ 으로 채우고 나머지는
                # 5 - i 만큼 ☆ 으로 채운다.
                elif db_data.grade == i:
                    db_data.star = '★' * i + '☆' * (5 - i)
                    break
                # 소수일 때 i + 1 만큼 ★ 으로 채우고 나머지는
                # 4 - i 만큼 ☆ 으로 채운다.
                elif db_data.grade <= i + 1:
                    db_data.star = '★' * (i + 1)  + '☆' * (4 - i)
                    break

            db_data.save()

            return redirect('reviews:index')

    else:
        data = ReviewForm()

    return render(req, 'reviews/create.html', {'data': data})


# ref(pagination) : https://velog.io/@jewon119/Django-%EA%B8%B0%EC%B4%88-ListView
def index(req):
    data = Review.objects.all().order_by('-id')

    # review_list 페이징 처리
    page = req.GET.get('page') #GET 방식으로 정보를 받아오는 데이터
    paginator = Paginator(data, '6') #Paginator(분할될 객체, 페이지 당 담길 객체수)
    page_obj = paginator.get_page(page) #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장

    return render(req, 'reviews/index.html', {'data': data, 'page': page_obj})


def detail(req, _id):
    db_data = Review.objects.get(id=_id)

    return render(req, 'reviews/detail.html', {'data': db_data})


def update(req, _id):
    db_data = Review.objects.get(id=_id)

    if req.method == 'POST':
        data = ReviewForm(req.POST, instance=db_data)

        if data.is_valid():
            data.save()

            return redirect('reviews:index')

    else:
        data = ReviewForm(instance=db_data)

    return render(req, 'reviews/create.html', {'data': data})


def delete(req, _id):
    Review.objects.get(id=_id).delete()

    return redirect('reviews:index')

reviews/templates/reviews/create.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}

{% if request.resolver_match.url_name == 'create' %}
    <h1>생성</h1>
{% else %}
    <h1>수정</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form data %}

    {% bootstrap_button button_type="submit" content="OK" %}
</form>

{% endblock %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<h1>About Movie</h1>
<h2>{{ data.title }}</h2>
<h3>{{ data.movie_name }}</h3>
<p>{{ data.grade }}</p>
<p>{{ data.created_at }} | <span>{{ data.updated_at }}</span></p>
<p>{{ data.content }}</p>

<div class="buttons d-flex">
  <a class="me-3" href="{% url 'reviews:update' data.id %}">{% bootstrap_button button_class="btn btn-outline-success" content="수정" %}</a>
  <div>
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
      삭제
    </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Warning</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Do you really want to delete it?
          </div>
          <div class="modal-footer">
            <a href="{% url 'reviews:delete' data.id %}">
              <button type="button" class="btn btn-primary">Yes</button>
            </a>  
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<h1>Movies</h1>
<table class="table align-middle">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">Movie Name</th>
      <th scope="col">Grade</th>
      <th scope="col">Star</th>
      <th scope="col">Created</th>
      <th scope="col">Updated</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <!-- 넘겨받은 페이지 객체만큼 반복한다. -->
    {% for i in page %}
    <tr>
      <td class="fw-bold"><a href="{% url 'reviews:detail' i.id %}">{{ i.title }}</a></td>
      <td>{{ i.content }}</td>
      <td>{{ i.movie_name }}</td>
      <td>{{ i.grade }}</td>
      <td>{{ i.star }}</td>
      <td>{{ i.created_at }}</td>
      <td>{{ i.updated_at }}</td>
    </tr>
    {% endfor %} 
  </tbody>
</table>
<div class="d-flex justify-content-end">
  <a href="{% url 'reviews:create' %}">
    <button type="button" class="btn btn-primary mb-3">New Movie</button>
  </a>
</div>

<!-- ref(Disabled and active states) : https://getbootstrap.com/docs/5.2/components/pagination/ -->
<!-- 페이징처리 시작 -->
<nav aria-label="pagination" class="d-flex justify-content-center">
  <ul class="pagination">
    <!-- previous -->
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">Previous</a>
    </li>
    {% endif %}

    <!-- pages -->
    <!-- page.paginator.page_range : [1, ..., max] -->
    {% for i in page.paginator.page_range %}
      {% if i == page.number %}
      <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ i }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    
    <!-- next -->
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
<!-- 페이징처리 끝 -->


{% endblock %}


templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
		{% load static %}
		{% block css %}
		{% endblock css %}
</head>
<body>
	<nav class="navbar navbar-expand navbar-dark bg-dark">
			<div class="container-fluid">
				<a class="navbar-brand" href="{% url 'reviews:index' %}">
					<img src="{% static 'images/logo.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
					Reviews
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav">
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="{% url 'reviews:index' %}">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link active" href="{% url 'reviews:create' %}">New</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	<div class="container mt-5">
	{% block content %}
	{% endblock %}
	</div>
	<footer class="p-3 bg-dark text-white text-center">
		<p> django Reviews PJT, by 김문경 이동근 신우철</p>
	</footer>
	<!-- JavaScript Bundle with Popper -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>